app/api_v1/builds.py, app/api_v1/editions.py, app/api_v1/products.py, app/auth.py, app/models.py, run.py, tests/conftest.py, tests/test_builds.py, tests/test_editions.py, tests/test_products.py
The initial MVP of ltd-keeper had all-or-nothing authentication; any user was effectively an admin user. This adds fine-grained roles that each API user could have (for example, one API user might be able to add a build, but not create an edition or product or add another user).
- Deferred: ~~Make it possible for some routes to be semi-opened. For example, a user who administers a Product might see 'private' infrastructural details about the Product that an anonymous user would not see. A way to do this is described in https://github.com/miguelgrinberg/Flask-HTTPAuth/issues/17#issuecomment-76668519~~ → [DM-5679](https://jira.lsstcorp.org/browse/DM-5679)
=> DM-5645: Add fine-grained authorization to ltd-keeper users

.travis.yml, docs/conf.py
This enables continuous documentation deployment to LSST the Docs under the ltd-keeper product name.
=> Enable ltd-mason in travis.yml

app/models.py, app/s3.py, tests/test_s3.py
When an edition is rebuild the following headers are set:
```
Surrogate-Control: max-age=31536000
Cache-Control: no-cache
```
This ensures that Fastly caches the content in its POPs for a year, while also telling browsers to check with Fastly whether a client-side cache is stale based on ETag hashes.
See
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
for more information.
In the future it may be a good idea to create more nuanced client-side caching rules based on content types. For example, CSS and JavaScript can probably be cached for at least a day without requiring the browser to re-validate that cache.
=> DM-6111: Edition rebuild changes Cache-Control to no-cache for Browsers

app/utils.py, tests/test_utils.py
Had a bug where `utils.auto_slugify_edition` did not replace underscores with a dash, and therefore `failed utils.validate_path_slug`.
Adds this replacement code and adds a test for such a case.
=> DM-6638: Auto slug for edition paths deals with underscores

app/utils.py, tests/test_utils.py
Previously only tickets/DM-NNNN tickets got editions with /v/DM-NNNN
paths. The regex now works with any ticket type, e.g. tickets/LCR-NNNN.
=> DM-7439: Support non-DM tickets for special edition routes

.travis.yml, app/api_v1/__init__.py, app/api_v1/builds.py, app/api_v1/dashboards.py, app/api_v1/editions.py, app/api_v1/products.py, app/dasher.py, app/exceptions.py, app/models.py, config.py, docs/dashboards.rst, docs/dev-migrations.rst, docs/docker-image.rst, docs/gke-cloudsql.rst, docs/gke-migrations.rst, docs/gke-staging-deployment-playbook.rst, docs/index.rst, docs/products.rst, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/ltd-staging-namespace.yaml, migrations/versions/ffdd80058eed_add_surrogate_key_to_product.py, requirements.txt, run.py, setup.cfg, tests/test_dashboards.py, tests/test_dasher.py, tests/test_fastly.py, tests/test_products.py, uwsgi.ini
This PR add hooks to the LTD Keeper server app that triggers an [LTD Dasher](https://github.com/lsst-sqre/ltd-dasher) Dashboard build whenever a build or edition gets updated (created, updated, deleted).
The Dasher server is automatically discovered with Kubernetes (i.e., Dasher has a `dasher` service, so its cluster URL is `http://dasher:3091`). If the Dasher config isn't set then dashboard builds are a no-op. This way Dasher is an optional extension to the LTD deployment.
There are two new routes dedicated to building dashboards, which are mostly intended to debugging and recovering from errors:
- [POST /dashboards](https://ltd-keeper.lsst.io/v/DM-9021/dashboards.html#post--dashboards)
- [POST /products/(slug)/dashboard](https://ltd-keeper.lsst.io/v/DM-9021/products.html#post--products-( …
=> DM-9021: Add hooks to trigger LTD Dasher

app/api_v1/editions.py, app/api_v1/products.py, app/gitrefutils.py, app/models.py, docs/builds.rst, docs/editions.rst, docs/products.rst, migrations/versions/aae44dcdaf52_add_edition_mode_column.py, tests/test_gitrefutils.py, tests/test_patch_edition_mode.py, tests/test_track_lsst_doc.py
This PR adds the explicit idea of **tracking modes** to edition resources. This determines whether or not an edition is updated with a new build. The default tracking mode was to update if a build resource has the right git ref (a tag or branch name).
The new tracking mode allows an edition to watch for builds with git refs formatted as ``v<Major>.<Minor>`` and always publish the newest such tag. This supports the revised LSST DM document release procedure: https://developer.lsst.io/v/DM-11952/docs/change-controlled-docs.html
Draft documentation for the LTD Keeper API update is at: https://ltd-keeper.lsst.io/v/DM-12356/editions.html
=> DM-12356: Support the LSST DM document release procedure

.gitignore, CHANGELOG.rst, keeper/__init__.py, keeper/api_v1/builds.py, keeper/api_v1/editions.py, keeper/api_v1/errorhandlers.py, keeper/api_v1/products.py, keeper/api_v1/root.py, keeper/auth.py, keeper/config.py, keeper/logutils.py, keeper/models.py, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/ltd-prod-namespace.yaml, setup.py
- Add structlog as a dependency.
- Configure structlog to output key-value strings in test/development and JSON-formatted strings in production.
- Add a `@log_route` decorator that creates a new logger and binds metadata about a request, such as a unique request ID, method and path. It also logs the response latency and status when the route returns.
- The auth decorators bind the username once the user is known.
=> DM-12974: Add structlog-based route logging

CHANGELOG.rst, docs/gke-update.rst, keeper/utils.py, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/keeper-worker-deployment.yaml, tests/test_utils.py
This is necessary to support semantic versions (`1.0.0`) as edition names and EUPS tags (v15_0 or `w_2018_01`) as edition names as well.
Fixes #32
=> DM-14772: Allow . and _ in edition slugs

CHANGELOG.rst, docs/editions.rst, keeper/editiontracking/__init__.py, keeper/editiontracking/eupsdailymode.py, keeper/editiontracking/eupsmajormode.py, keeper/editiontracking/eupsweeklymode.py, keeper/editiontracking/gitrefmode.py, keeper/editiontracking/lsstdocmode.py, keeper/editiontracking/trackingmodes.py, keeper/models.py, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/keeper-worker-deployment.yaml, tests/test_eupsdailymode.py, tests/test_eupsmajormode.py, tests/test_eupsweeklymode.py, tests/test_lsstdocmode.py, tests/test_track_eups_daily_tag.py, tests/test_track_eups_major_tag.py, tests/test_track_eups_weekly_tag.py
This release improves and expands the system of edition tracking modes.
There are three new tracking modes:
- ``eups_major_release`` tracks an EUPS major release tag (``vX_Y``) and its Git variant (``X.Y``).
- ``eups_weekly_release`` tracks an EUPS weekly release tag (``w_YYYY_WW``) and its Git variant (``w.YYYY.WW``).
- ``eups_daily_release`` tracks an EUPS daily release tag (``d_YYYY_MM_DD``) and its Git variant (``d.YYYY.MM.DD``).
In addition, the code for determining whether an edition should rebuild or not given the tracking mode has been refactored out of the ``Edition.should_rebuild`` model method and into a new ``keeper.editiontracking`` subpackage.
Each tracking mode is now built around a uniform interface.
=> DM-15016: Add EUPS tag tracking modes

.travis.yml, CHANGELOG.rst, Dockerfile, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/keeper-worker-deployment.yaml, setup.py
- Update to Python 3.6.6 (in Docker base image and Travis).
- Update boto to 1.7.54 (for Python 3.6.6 compatibility).
- Update Celery to 4.2.0 (to fix a compatibility issue with Kombu 4.2's release).
Fixes #36
=> DM-15072: Update to celery 4.2.0 and Python 3.6.6

CHANGELOG.rst, keeper/models.py, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/keeper-worker-deployment.yaml, tests/test_track_eups_weekly_tag.py, tests/test_track_lsst_doc.py
- Make an Edition's ``tracked_refs`` field ``None`` when its tracking mode is not ``git_refs`` (only the ``git_refs`` mode uses ``tracked_refs``).
- Do not require a ``tracked_refs`` when creating an Edition that does not use the ``git_refs`` tracking mode.
=> DM-15075: Make an edition's tracked_refs be None if the tracking mode is not git_refs

CHANGELOG.rst, keeper/api_v1/editions.py, keeper/editiontracking/manualmode.py, keeper/editiontracking/trackingmodes.py, keeper/models.py, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/keeper-worker-deployment.yaml, tests/test_editions_autoincrement.py, tests/test_manualmode.py
This PR adds features needed by the new notebook-based report system (https://github.com/lsst-sqre/sqre-uservice-nbreport)
- New `autoincrement=True` field when creating editions that automatically assigns a monotonically increasing integer slug to the edition (and auto-assigns a title).
- New `manual` tracking mode that prevents an edition from automatically updating with new builds. Users can still update the edition manually using a PATCH.
=> DM-15243: Add auto increment feature for edition slugs and 'manual' tracking mode

CHANGELOG.rst, keeper/api_v1/builds.py, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/keeper-worker-deployment.yaml
Removed unneeded code from the ``new_build`` route that was throwing an error if the build corresponded to an edition with a manual tracking mode (as opposed to Git refs).
=> DM-15416: Fix issue with new builds corresponding to "manual" editions

CHANGELOG.rst, keeper/s3.py, kubernetes/flower-deployment.yaml, kubernetes/flower-service.yaml, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/keeper-worker-deployment.yaml
- Fixes a bug in `keeper.s3.delete_directory` related to "directories" that have 1000 or more objects.
The S3 and Boto APIs for deleting objects cannot handle more than 1000 object keys at once.
Now this function internally paginates over objects to bypass this limitation.
- Adds an experimental Kubernetes deployment of [Flower](https://flower.readthedocs.io/) to help monitor the Celery task queue.
=> DM-15518: Handle deletions when there are more than 1000 files in an edition

CHANGELOG.rst, keeper/s3.py, kubernetes/keeper-deployment.yaml, kubernetes/keeper-mgmt-pod.yaml, kubernetes/keeper-worker-deployment.yaml, tests/test_s3.py
Fixes a problem with the new `keeper.s3.delete_directory` implementation when the S3 prefix has no corresponding objects.
=> DM-16061: Handle cases when there are no objects to delete

CHANGELOG.rst, LICENSE, README.rst, docs/conf.py, tests/test_track_lsst_doc.py
Added additional tests to ensure that editions tracking ``master`` branches were automatically being created for documents using the ``lsst_doc`` tracking mode for the main edition. No application fixes were required.
=> DM-20487: Improve testing of the lsst_doc tracking mode scenario

CHANGELOG.rst, keeper/api/post_products_builds.py, kubernetes/keeper-deployment.yaml, tests/test_builds_v2.py
Fixed a bug that prevented logging configuration and authorization tests with the "v2" endpoint for `POST products/<product>/builds/`.
=> DM-20901: Fix automatic edition creation with v2 routes

CHANGELOG.rst, manifests/keeper-cm.yaml, manifests/keeper-deployment.yaml, manifests/keeper-service.yaml, manifests/kustomization.yaml, manifests/redis-deployment.yaml, manifests/redis-service.yaml, uwsgi.ini
- Introduced a new Kustomize-based deployment for LTD Keeper in the `/manifests/` repository directory. This deployment is designed to work with the Roundtable application platform. See LSST the Docs's deployment on Roundtable at https://github.com/lsst-sqre/roundtable/tree/master/deployments/lsst-the-docs.
- Dropped the Nginx pod from the `keeper` pod. Now we assume that LTD Keeper is being deployed behind a solid reverse proxy, such as `nginx-ingress`, and that we don't need to introduce yet another webserver into the stack.
- Since Nginx is no longer in the application pod, we switch uWSGI to use the `http-socket` mode instead of ``socket``.
To be released as 1.16.0.
=> DM-21494: Support deployments with Kustomize

CHANGELOG.rst, LICENSE, docs/conf.py, keeper/config.py, keeper/tasks/editionrebuild.py, manifests/keeper-deployment.yaml
This version adds initial support for [LTD Events](https://github.com/lsst-sqre/ltd-events), which acts as an adapter between LSST the Docs and the SQuaRE Events (Kafka) messaging system in the [Roundtable](https://roundtable.lsst.io) platform. Now, when an edition is updated, LTD Keeper sends an `edition.updated` payload to the LTD Events webhook endpoint.
More event types will be added in the future.
The LTD Events webhook endpoint is configured through the `LTD_EVENTS_URL` environment variable. If this environment variable is left unset, a webhook request isn't sent.
Related LTD Events PR: https://github.com/lsst-sqre/ltd-events/pull/1
=> DM-23899: Send an edition.updated webhook to LTD Events (1.18.0 release)

CHANGELOG.rst, keeper/appfactory.py, keeper/config.py, manifests/kustomization.yaml, setup.py
When operating behind a trusted proxy, we want to use the `X-Forwarded-` headers from the proxy to set the hostname and scheme for the API's URLs. The `PROXY_FIX` environment variable lets you toggle the Werkzeug [ProxyFix](https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/#werkzeug.middleware.proxy_fix.ProxyFix) middleware
to do just that (default is "0", or "off").
The `TRUST_X_FOR`, `TRUST_X_PROTO`, `TRUST_X_HOST`, `TRUST_X_PORT`, and `TRUST_X_PREFIX` environment variable settings specify the number of proxies to trust for the given the header when `PROXY_FIX` is enabled.
=> DM-25740: Respect X-Forwarded-Proto header

CHANGELOG.rst, keeper/editiontracking/lsstdocmode.py, manifests/kustomization.yaml, tests/test_lsstdocmode.py
Fixes the "lsstdoc" tracking mode, where version strings with double-digit numbers weren't being parsed correctly.
=> DM-27608: Fix lsstdoc tracking mode with double-digit version components

.github/workflows/ci.yaml, CHANGELOG.rst, manifests/kustomization.yaml
This was missed in the initial conversion to GitHub Actions.
=> DM-27608: Fix docker image name

.github/workflows/ci.yaml, bin/docker-tag.sh
Only build Docker images for tagged releases and ticket branches.
Use the official Docker actions, and use a script to determine the
Docker tag.
Use the pre-commit action instead of running pre-commit with tox
to get the benefit of pre-commit environment caching.
Also relax a GitHub Actions dependency to avoid upgrade churn.
=> [DM-29084] Update Docker and pre-commit CI configuration

keeper/models.py, keeper/services/createproduct.py, migrations/versions/8c431c5e70a8_v2_tables.py, tests/v2api/test_project_path_layout.py
This updates how published URLs are computed for projects/products, editions, and builds, to support path-based project layouts.
Note that root_fastly_domain is set to nullable now to support this change.
=> Add support for path-based project layouts

CHANGELOG.rst, keeper/api/products.py, keeper/editiontracking/lsstdocmode.py, manifests/kustomization.yaml, tests/test_builds.py, tests/test_builds_v2.py, tests/test_editions.py, tests/test_patch_edition_mode.py, tests/test_products.py, tests/test_track_eups_daily_tag.py, tests/test_track_eups_major_tag.py, tests/test_track_eups_weekly_tag.py, tests/test_track_lsst_doc.py, tests/test_utils.py
- Change "master" to "main" as the tracked branch for default editions when a product is created.
- Update the lsstdoc tracking mode so that it accepts either master or main as the name of a default branch to track if a semantic version is not available yet.
=> DM-32710: Update main as default branch for editions (1.23.0 release)

keeper/api/_models.py, keeper/editiontracking/gitrefmode.py, keeper/editiontracking/gitrefsmode.py, keeper/editiontracking/trackingmodes.py, keeper/models.py, keeper/services/createbuild.py, keeper/services/createedition.py, keeper/services/updateedition.py, keeper/v2api/_models.py, migrations/versions/f8eeb27a49e7_add_edition_tracked_ref_column.py, tests/test_editions.py, tests/test_track_lsst_doc.py, tests/v2api/test_project.py
The new `git_ref` tracking mode will replace `git_refs`, and tracks only a single git ref rather than multiple refs, as the previous mode was doing. This is the new default tracking mode, through `git_refs` is still available.
A new `Edition.tracked_ref` column is added, replacing the JSON-encoded `Edition.tracked_refs`.
To enable the transition, the services populate both `tracked_ref` and `tracked_refs`.
=> Add git_ref tracking mode

.gitignore, keeper/dashboard/__init__.py, keeper/dashboard/context.py, keeper/dashboard/jinjafilters.py, keeper/dashboard/static/app.css, keeper/dashboard/template/base.jinja, keeper/dashboard/template/build_dashboard.jinja, keeper/dashboard/template/edition_dashboard.jinja, keeper/dashboard/templateproviders.py, keeper/s3.py, keeper/services/createproduct.py, keeper/services/dashboard.py, keeper/testutils.py, keeper/v2api/projects.py, manifests/base/kustomization.yaml, requirements/dev.txt, requirements/main.in, requirements/main.txt, tests/test_dashboard_service.py, tests/test_dashboard_template.py
This PR reimplements dashboard generation for LTD Keeper v2. This functionality was originally part of [LTD Dasher](https://github.com/lsst-sqre/ltd-dasher). Since LTD Keeper v2 now support multiple missions, the dashboard generation code is being moved into LTD Keeper itself for easier maintainability.
The ultimate intent is for each organization to develop and configure their own dashboard HTML templates and assets. The default template though, will be built-in. This PR implements that `BuiltinTemplateProvider` and also enables us to develop other infrastructure related to dashaboard templates such as Jinja context objects and S3 uploading.
=> Implement dashboard generation from built-in templates

.github/workflows/ci.yaml, .gitignore, .pre-commit-config.yaml, keeper/editiontracking/lsstdocmode.py, keeper/models.py, keeper/services/createedition.py, keeper/services/updateedition.py, keeper/v2api/_models.py, keeper/v2api/editions.py, tests/test_lsstdocmode.py
- The release `kind` is now being automatically set based on introspection of the tracking git ref when an edition is automatically created from a build.
- The release `kind` is now included in the edition response models, and can be set or reset in the POST/PATCH models for an edition.
- The `lsst_doc` tracking mode now accepts semver tags, not just the `vX.Y` tags typical of Rubin documentation releases.
=> DM-44453: Fix handling of release versions in v2 API.
